### ISSUE TITLE
why did not use Conv2DTranspose in the generator of DCGAN

### ISSUE THREAD

**Issue by lestel** [eriklindernoren/Keras-GAN#15]
related PAPER of DCGAN all say they use Conv2DTranspose  rather than Conv2d

**Comment by eriklindernoren** [comment]
It's pretty common to get checkerboard artifacts with transposed convolution layers (if not carefully choosing filter shape and stride). Because of this I have chosen to use KNN upsampling -> regular convolution, which does not pose the same problem. 

You can read more about these checkerboard artifacts (and also the KNN->Conv technique) here: https://distill.pub/2016/deconv-checkerboard/

**Comment by lestel** [comment]
you enlightened me， thank you.  look forward to your future work for example bi-DCGAN   HAHA
