### ISSUE TITLE
code usage in ACGAN

### ISSUE THREAD

**Issue by shi18** [eriklindernoren/Keras-GAN#82]
label = Input(shape=(1,), dtype='int32')
label_embedding = Flatten()(Embedding(self.num_classes, 100)(label))
model_input = multiply([noise, label_embedding])
img = model(model_input)

what's the meaning of these lines in ACGAN code?

Thank you

**Comment by Ordgod** [comment]
@eriklindernoren Thank you very much!!!

**Comment by Ordgod** [comment]
@eriklindernoren 
I think maybe it's better to understand if change this line to two lines, doesn't it:
original code:
`label_embedding = Flatten()(Embedding(self.num_classes, 100)(label))`

changed code:
`
label_flatten = Flatten()(label)
label_embedding = Embedding(self.num_classes, 100)(flatten)
`

**Comment by dieKoderin** [comment]
Hi,
Thanks for the nice code! I am trying to use this for my data set which has images of size (299, 299, 3) belonging to 4 classes, instead of (28, 28, 1). I have already modified the input_shape to this:
` self.img_rows = 299
  self.img_cols = 299
  self.channels = 3
  self.img_shape = (self.img_rows, self.img_cols, self.channels)
  self.num_classes = 4
  self.latent_dim = 100`

but I get the following error:

`C:\Users\usr\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py:479: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'
Traceback (most recent call last):
  File "C:/Users/usr/PycharmProjects/GAN/ACGAN_bach.py", line 289, in <module>
    sample_interval=20)
  File "C:/Users/usr/PycharmProjects/GAN/ACGAN_bach.py", line 233, in train
    d_loss_fake = self.discriminator.train_on_batch(gen_imgs, [fake, fake_labels])
  File "C:\Users\usr\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 1209, in train_on_batch
    class_weight=class_weight)
  File "C:\Users\usr\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\usr\AppData\Roaming\Python\Python36\site-packages\keras\engine\training_utils.py", line 137, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (299, 299, 3) but got array with shape (28, 28, 3)`

I have tried debugging the code. But I couldn't find where actually the shape (28, 28, 3) comes from. Should I change anything else regarding the shape? Or is the problem another problem?

**Comment by eriklindernoren** [comment]
@dieKoderin please open a separate issue. The other questions appear to have been addressed so I'll close this one.
